/* jshint undef: true, unused: true */
/* global module */

var CONST = {
    ATTACHMENTS_DIR: "attachments/",
    ATTR_BRANCH: "branch",
    ATTR_DESCRIPTION: "description",
    ATTR_END1: "end1",
    ATTR_END2: "end2",
    ATTR_HREF: "xlink:href",
    ATTR_ID: "id",
    ATTR_MARKERID: "marker-id",
    ATTR_STYLE_ID: "style-id",
    ATTR_THEME: "theme",
    ATTR_TIMESTAMP: "timestamp",
    ATTR_TYPE: "type",
    ATTR_VERSION: "version",
    ATTR_VISIBILITY: "visibility",
    ATTR_X: "svg:x",
    ATTR_Y: "svg:y",
    AUTHOR: "leungwensen@gmail.com",
    CONTENT_XML: "content.xml",
    FILE_PROTOCOL: "file://",
    HTML_FORMAT_NOTE: "html",
    HTTPS_PROTOCOL: "https://",
    HTTP_PROTOCOL: "http://",
    MANIFEST_XML: "META-INF/manifest.xml",
    MARKERS_DIR:  "markers/",
    MARKER_SHEET: "markers/markerSheet.xml",
    MARKER_SHEET_XML: "markerSheet.xml",
    META_INF_DIR: "META-INF/",
    META_XML: "meta.xml",
    NAMESPACE: "xmlns",
    NS_FO: "http://www.w3.org/1999/XSL/Format",
    NS_SVG: "http://www.w3.org/2000/svg",
    NS_URI: "http://www.w3.org/1999/xhtml",
    NS_XHTML: "http://www.w3.org/1999/xhtml",
    NS_XLINK: "http://www.w3.org/1999/xlink",
    PLAIN_FORMAT_NOTE: "plain",
    REVISIONS_DIR: "Revisions/",
    REVISIONS_XML: "revisions.xml",
    SHAPE_ELLIPSIS: "org.xmind.topicShape.ellipse",
    SHAPE_RECTANGLE: "org.xmind.topicShape.rectangle",
    SHAPE_ROUND_RECTANGLE: "org.xmind.topicShape.roundedRect",
    STYLES_XML: "styles.xml",
    TAG_CHILDREN: "children",
    TAG_LABELS: "labels",
    TAG_LEGEND: "legend",
    TAG_MARKERREF : "marker-ref",
    TAG_MARKERREFS: "marker-refs",
    TAG_MARKER_DESCRIPTION: "marker-description",
    TAG_MARKER_DESCRIPTIONS: "marker-descriptions",
    TAG_NOTES: "notes",
    TAG_POSITION: "position",
    TAG_RELATIONSHIP: "relationship",
    TAG_RELATIONSHIPS: "relationships",
    TAG_SHEET: "sheet",
    TAG_TITLE: "title",
    TAG_TOPIC: "topic",
    TAG_TOPICS: "topics",
    TAG_WORKBOOK: "xmap-content",
    TOPIC_ATTACHED: "attached",
    TOPIC_DETACHED: "detached",
    TOPIC_FLOATING: "floating",
    TOPIC_PROTOCOL: "xmind:#",
    TOPIC_ROOT: "root",
    VAL_FOLDED: "folded",
    VERSION: "2.0",
    XMAP: "urn:xmind:xmap:xmlns:content:2.0",
    XMIND_EXT: ".xmind",
    MAKERIDS: [
        "flag-black",
        "flag-blue",
        "flag-green",
        "flag-orange",
        "flag-purple",
        "flag-red",
        "other-calendar",
        "other-clock",
        "other-coffee-cup",
        "other-email",
        "other-exclam",
        "other-fax",
        "other-lightbulb",
        "other-people",
        "other-phone",
        "other-question",
        "priority-1",
        "priority-2",
        "priority-3",
        "priority-4",
        "priority-5",
        "priority-6",
        "smiley-angry",
        "smiley-boring",
        "smiley-cry",
        "smiley-laugh",
        "smiley-smile",
        "smiley-surprise",
        "task-3quar",
        "task-done",
        "task-half",
        "task-pause",
        "task-quarter",
        "task-start",
    ]
};

module.exports = CONST;

